name: PyTorch Linux Bundle Fetcher

on: workflow_dispatch

jobs:
  download-torch-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux WHL Bundle
        run: |
          # 使用 pip download 自动处理版本匹配和依赖地址
          # 这样能确保下到的是真正的 .whl 文件（几GB大小），而不是 HTML 网页
          pip download \
            torch==2.11.0+cu130 \
            torchaudio==2.11.0+cu130 \
            torchvision==0.26.0+cu130 \
            -d ./ \
            --index-url https://pytorch.org \
            --platform manylinux2014_x86_64 \
            --only-binary=:all: \
            --python-version 311 \
            --no-deps # 仅下载这三个大包，其他小包你在 Windows 下发

          # 确认文件大小（正确的应该是几百MB到2GB）
          ls -lh *.whl

      - name: Upload Bundle to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pytorch-linux-bundle
          path: "./*.whl"
          retention-days: 1
